services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: truehealth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000 --noreload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SECRET_KEY
      - DEBUG
      - DATABASE_NAME
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_HOST
      - DATABASE_PORT
      - DJANGO_SETTINGS_MODULE=config.settings
      - PYTHONPATH=/code
      - PYTHONUNBUFFERED=1

volumes:
  postgres_data: