# Generated by Django 4.2.7 on 2026-04-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_refillrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='refill_requested',
            field=models.BooleanField(default=False),
        ),
    ]
