# Generated by Django 4.2.7 on 2026-04-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_internalhospital_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('lab_tech', 'Lab Technician'), ('pharmacist', 'Pharmacist'), ('radiologist', 'Radiologist'), ('receptionist', 'Receptionist'), ('cashier', 'Cashier'), ('manager', 'Manager'), ('patient', 'Patient')], default='admin', max_length=20),
        ),
    ]
