# Generated by Django 4.2.7 on 2026-04-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('lab_tech', 'Lab Technician'), ('pharmacist', 'Pharmacist'), ('radiologist', 'Radiologist'), ('receptionist', 'Receptionist'), ('cashier', 'Cashier'), ('manager', 'Manager'), ('patient', 'Patient'), ('er_developer', 'ER Developer')], default='admin', max_length=20),
        ),
    ]
