# Generated by Django 4.2.7 on 2026-04-15 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0002_vitalreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis_name', models.CharField(max_length=200)),
                ('icd10_code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('clinical_notes', models.TextField(blank=True)),
                ('medication_suggested', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_diagnoses', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
