# Generated by Django 4.2.7 on 2026-04-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_diagnosisrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisrecord',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
    ]
