# Generated by Django 4.2.7 on 2026-04-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayreport',
            name='ai_findings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xrayreport',
            name='ai_impression',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xrayreport',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
