# Generated by Django 4.2.7 on 2026-04-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_xrayreport_ai_findings_xrayreport_ai_impression_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayreport',
            name='patient_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
